name: Test App APK Build

on:
  push:
    branches: [main]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v3

      - name: Prepare Android project (Clean UI)
        run: |
          mkdir -p app/src/main/{assets,java/com/example/testapp}

          # HTML
          cat <<EOF > app/src/main/assets/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Test App</title>
              <link rel="stylesheet" href="style.css">
          </head>
          <body>
              <nav class="navbar">
                  <div class="container">
                      <span class="brand">Test App</span>
                      <ul class="nav">
                          <li><a href="#">Home</a></li>
                          <li><a href="#">Docs</a></li>
                          <li><a href="#">Examples</a></li>
                      </ul>
                  </div>
              </nav>

              <header class="hero">
                  <div class="container">
                      <h1>Build fast, responsive sites easily</h1>
                      <p>A simple, modern UI toolkit.</p>
                      <button onclick="showAlert()">Get Started</button>
                  </div>
              </header>

              <script src="script.js"></script>
          </body>
          </html>
          EOF

          # CSS
          cat <<EOF > app/src/main/assets/style.css
          body {margin:0;font-family:sans-serif;color:#212529;background:#fff;}
          .container {width:90%;margin:auto;max-width:900px;}
          .navbar {background-color:#563d7c;padding:15px;color:#fff;}
          .navbar .brand {font-weight:bold;font-size:1.2em;}
          .navbar .nav {list-style:none;padding:0;margin:0;float:right;}
          .navbar .nav li {display:inline-block;margin-left:15px;}
          .navbar .nav a {color:#fff;text-decoration:none;}
          .hero {padding:80px 0;text-align:center;}
          .hero h1 {font-size:3em;margin-bottom:0.3em;}
          .hero button {padding:10px 20px;font-size:16px;background-color:#7952b3;color:#fff;border:none;border-radius:5px;}
          EOF

          # JS
          cat <<EOF > app/src/main/assets/script.js
          function showAlert(){alert('Welcome to your Test App!')}
          EOF

          # AndroidManifest
          cat <<EOF > app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <application android:allowBackup="true" android:label="Test App" android:icon="@android:drawable/ic_menu_info_details">
                  <activity android:name=".MainActivity" android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
              </application>
              <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="34"/>
          </manifest>
          EOF

          # MainActivity.java
          cat <<EOF > app/src/main/java/com/example/testapp/MainActivity.java
          package com.example.testapp;
          import android.app.Activity;
          import android.os.Bundle;
          import android.webkit.WebSettings;
          import android.webkit.WebView;
          public class MainActivity extends Activity {
              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  WebView webview = new WebView(this);
                  WebSettings settings = webview.getSettings();
                  settings.setJavaScriptEnabled(true);
                  webview.loadUrl("file:///android_asset/index.html");
                  setContentView(webview);
              }
          }
          EOF

          # Gradle Files
          mkdir -p app
          cat <<EOF > app/build.gradle
          plugins { id 'com.android.application' }
          android {
              namespace 'com.example.testapp'
              compileSdk 34
              defaultConfig {
                  applicationId "com.example.testapp"
                  minSdk 21
                  targetSdk 34
                  versionCode 1
                  versionName "1.0"
              }
              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_17
                  targetCompatibility JavaVersion.VERSION_17
              }
          }
          EOF
          echo "include ':app'" > settings.gradle

          cat <<EOF > build.gradle
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies { classpath 'com.android.tools.build:gradle:8.4.0' }
          }
          allprojects { repositories { google(); mavenCentral() } }
          EOF

          echo "org.gradle.jvmargs=-Xmx2048m" > gradle.properties

          wget https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip gradle-8.7-bin.zip
          ./gradle-8.7/bin/gradle wrapper

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Test-App-APK
          path: app/build/outputs/apk/debug/app-debug.apk
