name: Note App CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create Project Files
        run: |
          mkdir -p dist
          cat <<EOF > dist/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Minimal Note App</title>
            <style>
              body { font-family: sans-serif; padding: 20px; background-color: #f8f8f8; }
              textarea { width: 100%; height: 300px; padding: 15px; font-size: 16px; }
              button { padding: 10px 15px; margin-top: 10px; cursor: pointer; }
            </style>
          </head>
          <body>
            <h2>Minimal Note App</h2>
            <textarea id="note"></textarea>
            <br>
            <button onclick="saveNote()">Save Note</button>
            <button onclick="clearNote()">Clear Note</button>

            <script>
              const note = document.getElementById('note');
              window.onload = () => note.value = localStorage.getItem('note') || '';
              function saveNote() {
                localStorage.setItem('note', note.value);
                alert('Note saved!');
              }
              function clearNote() {
                note.value = '';
                localStorage.removeItem('note');
                alert('Note cleared!');
              }
            </script>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
